apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${NAME_DEPLOYMENT}
spec:
  selector:
    matchLabels:
      app: ${NAME_DEPLOYMENT}
  replicas: ${REPLICAS}
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ${NAME_DEPLOYMENT}
    spec:
      containers:
        - name: ${NAME_DEPLOYMENT}-container
          image: ${IMAGE_DOCKER}
          resources:
            requests:
              cpu: ${REQUEST_CORES}
              memory: ${REQUEST_MEMORY}
            limits:
              cpu: "${MAX_CORES}"
              memory: "${MAX_MEMORY}"
          env:
            - name: NODE_ENV
              value: production
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: ${NAME_DEPLOYMENT}-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: ${NAME_DEPLOYMENT}

